# permissions for end users to edit remediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remediation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aiops-operator
    app.kubernetes.io/part-of: aiops-operator
    app.kubernetes.io/managed-by: kustomize
  name: remediation-editor-role
rules:
- apiGroups:
  - aiops.example.com
  resources:
  - remediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiops.example.com
  resources:
  - remediations/status
  verbs:
  - get
